path:
  dataset: data/spambase.csv 

training:
  test_size: 0.2
  random_state: 42

features:
  ngram_range: [1, 2] 

model:
  type: XGBoost
  parameters:
    n_estimators: 100
    max_depth: 4
    learning_rate: 0.1
    use_label_encoder: False
    eval_metric: logloss
